from odoo import models, fields, api, _
from odoo.exceptions import UserError


# ─────────────────────────────────────────────────────────────────────────────
# 1.  MEDICINE SELLING PRICE CONFIG
# ─────────────────────────────────────────────────────────────────────────────
class MedicineTransferSellingPrice(models.Model):
    _name = 'medicine.transfer.selling.price'
    _description = 'Medicine Selling Price'
    _rec_name = 'product_id'
    _order = 'product_id'

    product_id = fields.Many2one(
        'product.product',
        string='Product',
        required=True,
        domain=[('type', '=', 'product')],
    )
    product_tmpl_id = fields.Many2one(
        'product.template',
        string='Product Template',
        related='product_id.product_tmpl_id',
        store=False,
        readonly=True,
    )
    selling_price = fields.Float(
        string='Selling Price',
        required=True,
        digits=(16, 2),
        help='Selling price per unit used to value internal medicine transfers.',
    )
    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        default=lambda self: self.env.company.currency_id,
    )
    notes = fields.Char(string='Notes')
    active = fields.Boolean(default=True)

    _sql_constraints = [
        (
            'unique_product',
            'unique(product_id)',
            'A selling price entry already exists for this product. Edit the existing one.',
        )
    ]


# ─────────────────────────────────────────────────────────────────────────────
# 2.  WIZARD
# ─────────────────────────────────────────────────────────────────────────────
class MedicineTransferSalesAuditWizard(models.TransientModel):
    _name = 'medicine.transfer.sales.audit.wizard'
    _description = 'Medicine Transfer vs Sales Audit – Run Wizard'

    start_date = fields.Date(string='From Date', required=True)
    end_date = fields.Date(string='To Date', required=True)
    clinic_ids = fields.Many2many(
        'clinic.clinic',
        string='Clinics (optional)',
        help='Select one or more clinics. Leave blank to include all clinics.',
    )

    @api.constrains('start_date', 'end_date')
    def _check_dates(self):
        for rec in self:
            if rec.start_date and rec.end_date and rec.start_date > rec.end_date:
                raise models.ValidationError('"From Date" must be before "To Date".')

    def action_run_audit(self):
        self.ensure_one()
        audit = self.env['medicine.transfer.sales.audit'].create({
            'start_date': self.start_date,
            'end_date': self.end_date,
            'clinic_ids': [(6, 0, self.clinic_ids.ids)],
            'clinic_name_filter': ', '.join(self.clinic_ids.mapped('name')),
        })
        audit._generate_lines()
        # Open the HEADER form (shows uncosted products alert + inline results)
        return {
            'type': 'ir.actions.act_window',
            'name': 'Medicine Transfer vs Sales Audit',
            'res_model': 'medicine.transfer.sales.audit',
            'res_id': audit.id,
            'view_mode': 'form',
            'target': 'current',
        }


# ─────────────────────────────────────────────────────────────────────────────
# 3.  AUDIT HEADER
# ─────────────────────────────────────────────────────────────────────────────
class MedicineTransferSalesAudit(models.Model):
    _name = 'medicine.transfer.sales.audit'
    _description = 'Medicine Transfer vs Sales Audit'
    _order = 'create_date desc'

    name = fields.Char(
        string='Reference',
        compute='_compute_name',
        store=True,
    )
    start_date = fields.Date(string='From Date', readonly=True)
    end_date = fields.Date(string='To Date', readonly=True)
    clinic_name_filter = fields.Char(string='Clinic Filter', readonly=True)
    clinic_ids = fields.Many2many(
        'clinic.clinic', string='Clinics', readonly=True)
    run_on = fields.Datetime(
        string='Generated On',
        readonly=True,
        default=fields.Datetime.now,
    )
    run_by_id = fields.Many2one(
        'res.users',
        string='Generated By',
        readonly=True,
        default=lambda self: self.env.user,
    )
    line_ids = fields.One2many(
        'medicine.transfer.sales.audit.line',
        'audit_id',
        string='Audit Lines',
        readonly=True,
    )

    uncosted_product_count = fields.Integer(
        string='Uncosted Products', readonly=True, default=0)
    uncosted_product_names = fields.Text(
        string='Products Without Selling Price', readonly=True)

    active = fields.Boolean(default=True)
    ui_hidden = fields.Boolean(
        string='Hidden from UI',
        default=False,
    )

    @api.depends('start_date', 'end_date', 'clinic_name_filter')
    def _compute_name(self):
        for rec in self:
            period = '%s → %s' % (rec.start_date or '?', rec.end_date or '?')
            if rec.clinic_name_filter:
                rec.name = 'Medicine Audit (%s) [%s]' % (period, rec.clinic_name_filter)
            else:
                rec.name = 'Medicine Audit (%s)' % period

    def action_archive(self):
        self.write({'active': False})

    def action_unarchive(self):
        self.write({'active': True})

    def action_ui_delete(self):
        for rec in self:
            if rec.active:
                raise UserError(_(
                    'Please archive this audit first. '
                    'Records can only be removed from the UI from the Archived view.'
                ))
        self.write({'ui_hidden': True})

    @api.model
    def _search(self, domain, offset=0, limit=None, order=None, access_rights_uid=None):
        domain = list(domain or [])
        if not self.env.context.get('include_ui_hidden'):
            domain = domain + [('ui_hidden', '=', False)]
        return super()._search(
            domain, offset=offset, limit=limit, order=order,
            access_rights_uid=access_rights_uid,
        )

    def action_open_lines(self):
        self.ensure_one()
        period = '%s → %s' % (self.start_date or '?', self.end_date or '?')
        return {
            'type': 'ir.actions.act_window',
            'name': _('Medicine Audit (%s)') % period,
            'res_model': 'medicine.transfer.sales.audit.line',
            'view_mode': 'tree',
            'views': [
                (self.env.ref(
                    'account_automation.view_medicine_transfer_sales_audit_line_full_tree'
                ).id, 'tree'),
            ],
            'search_view_id': [
                self.env.ref(
                    'account_automation.view_medicine_transfer_sales_audit_line_search'
                ).id
            ],
            'domain': [('audit_id', '=', self.id)],
            'context': {'create': False, 'edit': False, 'delete': False},
            'target': 'current',
        }

    def _generate_lines(self):
        self.ensure_one()
        self.line_ids.unlink()

        clinic_filter_clause = (
            "WHERE cc.id IN %(clinic_ids)s"
            if self.clinic_ids
            else ''
        )
        params = {
            'start_date': self.start_date,
            'end_date': self.end_date,
            'clinic_ids': tuple(self.clinic_ids.ids) or (0,),
        }

        query = f"""
            WITH

            clinic_master AS (
                SELECT
                    cc.id               AS clinic_id,
                    cc.name             AS clinic_name,
                    cc.pos_config_id    AS pos_config_id
                FROM clinic_clinic cc
                {clinic_filter_clause}
            ),

            sales_raw AS (
                SELECT
                    pc.id AS pos_config_id,
                    CASE
                        WHEN ROW_NUMBER() OVER (PARTITION BY am.id ORDER BY pay.method_name) = 1
                        THEN CASE
                                WHEN am.move_type = 'out_refund' THEN -ABS(am.amount_total)
                                ELSE ABS(am.amount_total)
                             END
                        ELSE 0
                    END AS invoice_total
                FROM account_move am
                LEFT JOIN pos_order   po  ON po.account_move = am.id
                LEFT JOIN pos_session pos ON pos.id          = po.session_id
                LEFT JOIN pos_config  pc  ON pc.id           = pos.config_id
                LEFT JOIN (
                    SELECT
                        am_inner.id AS inv_id,
                        COALESCE(
                            ppm.name->>'en_US',
                            CASE
                                WHEN aj.name->>'en_US' IN ('Manual', 'Point of Sale') THEN apml.name
                                ELSE aj.name->>'en_US'
                            END,
                            apml.name,
                            aj.name::text
                        ) AS method_name
                    FROM account_move am_inner
                    JOIN  account_move_line          aml_inv  ON aml_inv.move_id   = am_inner.id
                    JOIN  account_account            acc      ON acc.id             = aml_inv.account_id
                    JOIN  account_partial_reconcile  apr      ON (
                              apr.debit_move_id  = aml_inv.id
                           OR apr.credit_move_id = aml_inv.id
                    )
                    JOIN  account_move_line aml_pay ON (
                              (aml_pay.id = apr.credit_move_id AND aml_pay.id <> aml_inv.id)
                           OR (aml_pay.id = apr.debit_move_id  AND aml_pay.id <> aml_inv.id)
                    )
                    JOIN  account_journal                aj    ON aj.id   = aml_pay.journal_id
                    LEFT JOIN account_payment            ap    ON ap.id   = aml_pay.payment_id
                    LEFT JOIN account_payment_method_line apml ON apml.id = ap.payment_method_line_id
                    LEFT JOIN pos_payment                pp    ON pp.account_move_id = aml_pay.move_id
                    LEFT JOIN pos_payment_method         ppm   ON ppm.id = pp.payment_method_id
                    WHERE am_inner.state   = 'posted'
                      AND acc.account_type = 'asset_receivable'
                ) pay ON pay.inv_id = am.id
                WHERE am.move_type   IN ('out_invoice', 'out_refund')
                  AND am.state        = 'posted'
                  AND am.invoice_date >= %(start_date)s
                  AND am.invoice_date <= %(end_date)s
            ),

            sales_cte AS (
                SELECT pos_config_id, SUM(invoice_total) AS total_sales
                FROM sales_raw
                GROUP BY pos_config_id
            ),

            medicine_cte AS (
                SELECT
                    cc.id AS clinic_id,
                    SUM(sm.quantity * COALESCE(msp.selling_price, 0)) AS medicine_transfer_value
                FROM clinic_clinic cc
                JOIN stock_warehouse          sw  ON sw.id               = cc.warehouse_id
                JOIN stock_picking            sp  ON sp.location_dest_id = sw.lot_stock_id
                JOIN stock_picking_type       spt ON spt.id              = sp.picking_type_id
                JOIN stock_move               sm  ON sm.picking_id       = sp.id
                JOIN product_product          pp  ON pp.id               = sm.product_id
                JOIN product_template         pt  ON pt.id               = pp.product_tmpl_id
                LEFT JOIN medicine_transfer_selling_price msp
                       ON msp.product_id = pp.id
                      AND msp.active     = true
                WHERE spt.code       = 'internal'
                  AND sp.state       = 'done'
                  AND pt.type        = 'product'
                  AND sp.date_done::date >= %(start_date)s
                  AND sp.date_done::date <= %(end_date)s
                GROUP BY cc.id
            )

            SELECT
                cm.clinic_id,
                cm.clinic_name,
                COALESCE(s.total_sales,              0) AS total_sales,
                COALESCE(m.medicine_transfer_value,  0) AS medicine_transfer_value
            FROM      clinic_master  cm
            LEFT JOIN sales_cte      s   ON s.pos_config_id  = cm.pos_config_id
            LEFT JOIN medicine_cte   m   ON m.clinic_id      = cm.clinic_id
            ORDER BY cm.clinic_name
        """

        self.env.cr.execute(query, params)
        rows = self.env.cr.dictfetchall()

        # ── Detect uncosted products ──
        uncosted_query = """
            SELECT DISTINCT pt.id AS tmpl_id
            FROM clinic_clinic cc
            JOIN stock_warehouse    sw  ON sw.id               = cc.warehouse_id
            JOIN stock_picking      sp  ON sp.location_dest_id = sw.lot_stock_id
            JOIN stock_picking_type spt ON spt.id              = sp.picking_type_id
            JOIN stock_move         sm  ON sm.picking_id       = sp.id
            JOIN product_product    pp  ON pp.id               = sm.product_id
            JOIN product_template   pt  ON pt.id               = pp.product_tmpl_id
            LEFT JOIN medicine_transfer_selling_price msp
                   ON msp.product_id = pp.id
                  AND msp.active     = true
            WHERE spt.code      = 'internal'
              AND sp.state      = 'done'
              AND pt.type       = 'product'
              AND sp.date_done::date >= %(start_date)s
              AND sp.date_done::date <= %(end_date)s
              AND msp.id IS NULL
        """
        self.env.cr.execute(uncosted_query, params)
        uncosted_ids = [r['tmpl_id'] for r in self.env.cr.dictfetchall()]
        if uncosted_ids:
            names = self.env['product.template'].browse(uncosted_ids).mapped('name')
            self.uncosted_product_names = ', '.join(sorted(n for n in names if n))
            self.uncosted_product_count = len(uncosted_ids)
        else:
            self.uncosted_product_names = ''
            self.uncosted_product_count = 0

        # ── Build lines ──
        lines = []
        for row in rows:
            ts = row['total_sales'] or 0.0
            mtv = row['medicine_transfer_value'] or 0.0
            ratio = (ts / mtv) if mtv else 0.0
            lines.append((0, 0, {
                'clinic_db_id':              row['clinic_id'],
                'clinic_name':               row['clinic_name'],
                'total_sales':               ts,
                'medicine_transfer_value':   mtv,
                'sales_medicine_ratio':      ratio,
            }))
        self.line_ids = lines


# ─────────────────────────────────────────────────────────────────────────────
# 4.  AUDIT LINE
# ─────────────────────────────────────────────────────────────────────────────
class MedicineTransferSalesAuditLine(models.Model):
    _name = 'medicine.transfer.sales.audit.line'
    _description = 'Medicine Transfer vs Sales Audit – Line'
    _order = 'clinic_name'

    audit_id = fields.Many2one(
        'medicine.transfer.sales.audit',
        string='Audit',
        ondelete='cascade',
        index=True,
    )
    clinic_db_id = fields.Integer(string='Clinic DB ID')
    clinic_name = fields.Char(string='Clinic Name')

    total_sales = fields.Float(string='Total Sales', digits=(16, 2))
    medicine_transfer_value = fields.Float(
        string='Medicine Transfer Value', digits=(16, 2))
    sales_medicine_ratio = fields.Float(
        string='Sales / Medicine', digits=(16, 2))