from odoo import models, fields, api
from odoo.exceptions import UserError
from markupsafe import Markup


class EmiAudit(models.Model):
    _name = 'emi.audit'
    _description = 'EMI Provider Audit'
    _order = 'create_date desc'
    _inherit = ['mail.thread', 'mail.activity.mixin', 'chatter.toggle.mixin', 'emi.soft.delete.mixin']

    name = fields.Char(required=True, tracking=True)
    provider_id = fields.Many2one('emi.provider.config', string='EMI Provider', required=True, tracking=True)
    start_date = fields.Date(required=True, tracking=True)
    end_date = fields.Date(required=True, tracking=True)
    file_name = fields.Char()

    run_by = fields.Many2one('res.users', default=lambda self: self.env.user, readonly=True)
    run_date = fields.Datetime(default=fields.Datetime.now, readonly=True)

    line_ids = fields.One2many('emi.audit.line', 'audit_id', string='Clinic Summary')


class EmiAuditLine(models.Model):
    _name = 'emi.audit.line'
    _description = 'EMI Audit Clinic Summary'
    _order = 'difference desc, clinic_name asc, invoice_no asc'

    audit_id = fields.Many2one('emi.audit', required=True, ondelete='cascade')
    audit_date = fields.Date(related='audit_id.start_date', store=True, readonly=True)
    provider_id = fields.Many2one(related='audit_id.provider_id', store=True)

    clinic_id = fields.Many2one('pos.config', string='Clinic')
    clinic_name = fields.Char(string='Clinic Name')
    invoice_no = fields.Char(string='Invoice No')
    invoice_date = fields.Date(string='Invoice Date')
    settlement_date = fields.Char(string='Settlement Date')

    odoo_emi_sales = fields.Float(string='Odoo Sales', digits=(16, 2))
    expected_odoo_amount = fields.Float(string='Expected Sales (CSV)', digits=(16, 2))
    difference = fields.Float(string='Difference', digits=(16, 2))

    advance_paid = fields.Float(string='Advance Paid', digits=(16, 2))
    fees_deducted = fields.Float(string='Fees Deducted', digits=(16, 2))
    final_payout = fields.Float(string='Final Payout', digits=(16, 2))

    resolution_state = fields.Selection([('open', 'Open'), ('resolved', 'Resolved')], default='open', string='Status')
    reason_id = fields.Many2one('emi.audit.reason', string='Reason')
    note = fields.Char(string='Note')
    net_difference = fields.Float(string='Remaining Gap', digits=(16, 2))

    created_pending_id = fields.Many2one('emi.audit.pending', string='Pending Entry Created', readonly=True)
    pending_status = fields.Selection(related='created_pending_id.state', string='Pending Status', readonly=True)
    settled_pending_ids = fields.One2many('emi.audit.pending', 'settled_by_line_id',
                                          string='Settled Against Past Entries')

    resolved_for_date = fields.Date(string="Gap From Date", compute="_compute_resolved_dates")
    resolved_on_date = fields.Date(string="Cleared On Date", compute="_compute_resolved_dates")

    @api.depends('settled_pending_ids', 'created_pending_id.state')
    def _compute_resolved_dates(self):
        for line in self:
            past = line.settled_pending_ids.filtered(lambda p: p.audit_line_id)
            if past and past[0].audit_line_id:
                line.resolved_for_date = past[0].audit_line_id.audit_date
            else:
                line.resolved_for_date = False

            if (line.created_pending_id
                    and line.created_pending_id.state == 'settled'
                    and line.created_pending_id.settled_by_line_id):
                line.resolved_on_date = line.created_pending_id.settled_by_line_id.audit_date
            else:
                line.resolved_on_date = False

    def action_open_resolve_wizard(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'emi.audit.resolve.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {'default_line_id': self.id},
        }

    def action_reset_line_to_open(self):
        for line in self:
            if line.resolution_state == 'open' and not line.reason_id:
                continue

            if line.created_pending_id:
                target = line.created_pending_id
                line.write({'created_pending_id': False})
                if target.state == 'open':
                    target.unlink()
                elif target.state == 'settled':
                    raise UserError(
                        f"Cannot reset {line.invoice_no or line.clinic_name}. "
                        f"The pending entry generated by this line has already been settled in a future audit."
                    )

            if line.settled_pending_ids:
                line.settled_pending_ids.write({
                    'state': 'open',
                    'settled_by_line_id': False,
                })

            line.write({
                'reason_id': False,
                'note': False,
                'resolution_state': 'open',
                'net_difference': 0.0,
            })

            if line.audit_id:
                identifier = (
                    f"Invoice <code>{line.invoice_no}</code>"
                    if line.invoice_no
                    else f"Clinic <code>{line.clinic_name or 'N/A'}</code>"
                )
                line.audit_id.message_post(
                    body=Markup(
                        f"<strong>Line Reset:</strong> "
                        f"{identifier} has been reset back to open."
                    ),
                    subtype_xmlid="mail.mt_note"
                )


class EmiAuditPending(models.Model):
    _name = 'emi.audit.pending'
    _description = 'EMI Audit Pending Variance'
    _order = 'create_date asc'
    _inherit = ['emi.soft.delete.mixin']

    audit_line_id = fields.Many2one('emi.audit.line', string='Origin Line', ondelete='cascade', required=True)
    provider_id = fields.Many2one('emi.provider.config', string='EMI Provider', required=True)
    clinic_id = fields.Many2one('pos.config', string='Clinic')
    clinic_name = fields.Char(string='Clinic Name')
    amount = fields.Float(string='Pending Amount', digits=(16, 2))

    reason_id = fields.Many2one('emi.audit.reason', string='Reason')
    note = fields.Char(string='Note')

    state = fields.Selection([('open', 'Open'), ('settled', 'Settled')], default='open', string='Status')

    settled_by_line_id = fields.Many2one('emi.audit.line', string='Settled By Line')
    settled_audit_date = fields.Date(related='settled_by_line_id.audit_id.start_date', store=True, readonly=True)
    settled_in_audit_id = fields.Many2one(
        'emi.audit',
        string='Settled Via Audit',
        compute='_compute_settled_in_audit_id',
        store=True,
        readonly=True
    )

    active = fields.Boolean(default=True)

    @api.depends('settled_by_line_id.audit_id')
    def _compute_settled_in_audit_id(self):
        for rec in self:
            if rec.settled_by_line_id and rec.settled_by_line_id.audit_id:
                rec.settled_in_audit_id = rec.settled_by_line_id.audit_id.id
            else:
                rec.settled_in_audit_id = False