{
    'name': 'Account Automation Utilities',
    'version': '17.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Custom financial automations, PSMR reconciliations, and internal data audits.',
    'depends': ['account', 'point_of_sale', 'mail', 'clinic_management'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/bank_hub_reason_data.xml',
        'data/emi_audit_reason_data.xml',
        'views/bank_hub_config_views.xml',
        'views/bank_hub_audit_views.xml',
        'views/bank_hub_reconciliation_views.xml',
        'views/emi_audit_config_views.xml',
        'views/emi_audit_views.xml',
        'views/emi_audit_reconciliation_views.xml',
        'views/account_automation_views.xml',
        'views/psmr_mapping_views.xml',
        'views/psmr_reconciliation_views.xml',
        'views/clinic_performance_views.xml',
        'views/invoice_lock_views.xml',
        'views/medicine_transfer_sales_audit_views.xml',
        'data/mail_template_session_alert.xml',
        'data/ir_cron_session_alert.xml',
        'views/pos_session_alert_views.xml',
        'views/pos_session_cash_checkpoint_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
