from odoo import models, fields, api


class CashDepositResolveWizard(models.TransientModel):
    _name = 'cash.deposit.resolve.wizard'
    _description = 'Resolve Cash Deposit Variance'

    line_id = fields.Many2one(
        'cash.deposit.audit.line',
        required=True,
        readonly=True
    )

    # Context (display-only)
    audit_date = fields.Date(related='line_id.audit_date', readonly=True)
    clinic_display = fields.Char(related='line_id.clinic_display', readonly=True)
    pos_cash_in = fields.Float(related='line_id.pos_cash_in', readonly=True)
    pos_cash_out = fields.Float(related='line_id.pos_cash_out', readonly=True)
    total_expected_deposit = fields.Float(related='line_id.total_expected_deposit', readonly=True)
    bank_received = fields.Float(related='line_id.bank_received', readonly=True)
    difference = fields.Float(related='line_id.difference', readonly=True)

    amount_to_resolve = fields.Float(
        string='Amount To Resolve',
        compute='_compute_amount_to_resolve',
        readonly=True
    )

    @api.depends('line_id.resolution_state', 'line_id.difference', 'line_id.net_difference')
    def _compute_amount_to_resolve(self):
        for w in self:
            line = w.line_id
            if not line:
                w.amount_to_resolve = 0.0
            elif line.resolution_state == 'resolved':
                w.amount_to_resolve = line.net_difference
            else:
                w.amount_to_resolve = line.difference

    reason_id = fields.Many2one('cash.deposit.audit.reason', string='Reason', required=True)
    resolution_type = fields.Selection(related='reason_id.resolution_type', readonly=True)
    note = fields.Char(string='Note')

    pending_ids = fields.Many2many(
        'cash.deposit.pending',
        string="Available Open Pendings",
        compute="_compute_pending_ids",
        store=True,
        readonly=False,
        domain=[('state', '=', 'open')]
    )

    remaining_after_settle = fields.Float(
        string='Remaining After Settlement',
        compute='_compute_remaining_after_settle'
    )

    @api.depends('line_id')
    def _compute_pending_ids(self):
        for wiz in self:
            if not wiz.line_id or not wiz.line_id.clinic_id:
                wiz.pending_ids = [(5, 0, 0)]
                continue
            matches = self.env['cash.deposit.pending'].search([
                ('clinic_id', '=', wiz.line_id.clinic_id.id),
                ('state', '=', 'open'),
            ])
            wiz.pending_ids = [(6, 0, matches.ids)]

    @api.depends('pending_ids', 'amount_to_resolve')
    def _compute_remaining_after_settle(self):
        for w in self:
            w.remaining_after_settle = w.amount_to_resolve + sum(w.pending_ids.mapped('amount'))

    def action_apply(self):
        self.ensure_one()
        line = self.line_id
        reason = self.reason_id
        Pending = self.env['cash.deposit.pending']

        amount = line.net_difference if line.resolution_state == 'resolved' else line.difference

        # Wipe previous open pending generated by this line (2nd pass safety)
        if line.created_pending_id:
            old_pending = line.created_pending_id
            line.write({'created_pending_id': False})
            if old_pending.state == 'open':
                old_pending.unlink()

        if reason.resolution_type == 'write_off':
            line.write({
                'reason_id': reason.id,
                'note': self.note,
                'resolution_state': 'resolved',
                'net_difference': 0.0,
            })

        elif reason.resolution_type == 'carry_forward':
            pending = Pending.create({
                'audit_line_id': line.id,
                'clinic_id': line.clinic_id.id if line.clinic_id else False,
                'clinic_display': line.clinic_display,
                'amount': amount,
                'reason_id': reason.id,
                'note': self.note,
                'state': 'open',
            })
            line.write({
                'reason_id': reason.id,
                'note': self.note,
                'resolution_state': 'resolved',
                'net_difference': amount,
                'created_pending_id': pending.id,
            })

        elif reason.resolution_type == 'settle_pending':
            selected = self.pending_ids
            net = amount + sum(selected.mapped('amount'))

            selected.write({
                'state': 'settled',
                'settled_by_line_id': line.id,
            })

            line_vals = {
                'reason_id': reason.id,
                'note': self.note,
                'resolution_state': 'resolved',
                'net_difference': net,
            }

            if abs(net) > 0.0001:
                remainder = Pending.create({
                    'audit_line_id': line.id,
                    'clinic_id': line.clinic_id.id if line.clinic_id else False,
                    'clinic_display': line.clinic_display,
                    'amount': net,
                    'reason_id': reason.id,
                    'note': f"Remainder after settling {self.note or ''}".strip(),
                    'state': 'open',
                })
                line_vals['created_pending_id'] = remainder.id

            line.write(line_vals)

        return {'type': 'ir.actions.act_window_close'}